# this script is generated by ai
FROM archlinux:latest
RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm \
    base-devel \
    cmake \
    ninja \
    git \
    vulkan-devel
WORKDIR /app
COPY  . .
RUN rm -rf build && \
    cmake -B build -G Ninja -DGGML_VULKAN=ON -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build
RUN pip3 install --break-system-packages huggingface_hub
ARG SKIP_MODEL_DOWNLOAD=0
ARG MODEL_PATH=0
ENV SKIP_MODEL_DOWNLOAD=$SKIP_MODEL_DOWNLOAD
ARG MODEL_PATH=$MODEL_PATH
COPY --from=builder /app/build/engine ./engine
RUN mkdir ./models
ENTRYPOINT python3 download.py && ./engine
