# this script is generated by ai
FROM alpine:3.19
RUN apk add --no-cache \
    build-base \
    cmake \
    git \
    linux-headers \
    python3 \
    py3-pip

RUN pip3 install --break-system-packages huggingface_hub
WORKDIR /app
COPY download.py main.cpp CMakeLists.txt ./
COPY include/ ./include/
ARG SKIP_MODEL_DOWNLOAD=0
ENV SKIP_MODEL_DOWNLOAD=$SKIP_MODEL_DOWNLOAD
RUN python3 download.py
RUN git clone https://github.com/nlohmann/json.git /tmp/json && \
    cp /tmp/json/single_include/nlohmann/json.hpp ./include/ && \
    rm -rf /tmp/json

RUN cmake -B build -S . -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build --parallel $(nproc)
ENTRYPOINT ["./build/engine_bin"]
