#this script is generated by ai
import os
from huggingface_hub import hf_hub_download

REPO_ID = "unsloth/Qwen3.5-9B-GGUF" 
FILENAME = "Qwen3.5-9B-Q8_0.gguf"
DEST_DIR = "./models"
if os.getenv("SKIP_MODEL_DOWNLOAD") == "1":
    print("[log] SKIP_MODEL_DOWNLOAD flag detected. Skipping download phase entirely.")
elif os.path.exists(os.path.join(DEST_DIR, FILENAME)):
    print(f"[log] {FILENAME} already exists locally. Skipping download.")
else:
    print(f"[log] Spinning up download handler for {FILENAME}...")
    try:
        os.makedirs(DEST_DIR, exist_ok=True)
        model_local_path = hf_hub_download(
            repo_id=REPO_ID,
            filename=FILENAME,
            local_dir=DEST_DIR,
            local_dir_use_symlinks=False 
        )
        print(f"\n[success] Weights downloaded to: {os.path.abspath(model_local_path)}")
    except Exception as e:
        print(f"\n[error] Download failed: {e}")
        exit(1)
