#this script is generated by ai
import os
from huggingface_hub import hf_hub_download

REPO_ID = "unsloth/Qwen3.5-9B-GGUF" 
FILENAME = "Qwen3.5-9B-Q4_K_M.gguf"
DEST_DIR = "./models"

print(f"[log] Spinning up download handler for {FILENAME}...")
print(f"[log] Target repository: https://huggingface.co/{REPO_ID}")
if not os.path.exists(os.path.join(DEST_DIR,FILENAME)):
    try:
        os.makedirs(DEST_DIR, exist_ok=True)
        model_local_path = hf_hub_download(
            repo_id=REPO_ID,
            filename=FILENAME,
            local_dir=DEST_DIR,
            local_dir_use_symlinks=False 
        )
        print("\n" + "="*50)
        print("[success] Weights downloaded successfully!")
        print(f"[success] Target location: {os.path.abspath(model_local_path)}")
        print("="*50)
    except Exception as e:
        print(f"\n[error] Download failed or was interrupted: {e}")
